---
- hosts: all
  module_defaults:
    ansible.builtin.file:
      pip: python3-pip
      python: python3
  become: true
  tasks:

  - name: install latest phyton3, pip3, and java open-jdk in Ubuntu
    apt:
      name:
        - python3
        - python3-pip
        - default-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install latest phyton3, pip3, and java open-jdk in CentOS
    yum:
      name: 
        - python3 
        - python3-pip 
        - java-11-openjdk-devel
      state: latest 
      update_cache: yes
    when: ansible_distribution == "CentOS" 

  - name: Creating a User with variable define in config.yaml
    ansible.builtin.user:
          name: ausan
          uid: 1204
          group: root
          home: /home/reizen
